---
pipeline:
  name: sc2-download
transform:
  image: chriszs/sc2-cast-analyzer
  cmd:
  - bash
  stdin:
  - ./transforms/download.sh /pfs/out/
parallelism_spec:
  constant: 2
datum_tries: 2
input:
  cron:
    name: tick
    spec: "@daily"
