---
pipeline:
  name: sc2-frame
transform:
  image: chriszs/sc2-cast-analyzer
  cmd:
  - bash
  stdin:
  - ./transforms/frame.sh /pfs/split/ /pfs/out/
parallelism_spec:
  constant: 2
datum_tries: 2
input:
  pfs:
    name: split
    repo: sc2-split
    glob: /*
    lazy: true
