---
pipeline:
  name: sc2-split
transform:
  image: chriszs/sc2-cast-analyzer
  cmd:
  - bash
  stdin:
  - ./transforms/split.sh /pfs/download/ /pfs/out/
parallelism_spec:
  constant: 2
datum_tries: 2
input:
  pfs:
    name: check
    repo: sc2-download
    glob: /*
    empty_files: true
